# Generated by Django 5.0.2 on 2024-08-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_livro_capa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="editora",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
